export const CONSTANT = {
  locales: ["en", "bn", "ar"],
  defaultLocale: "ar",
  blogs: {
    1: "/images/blogs/1.webp",
    2: "/images/blogs/2.webp",
    3: "/images/blogs/3.webp",
    4: "/images/blogs/4.webp",
    5: "/images/blogs/5.webp",
    6: "/images/blogs/6.webp",
    7: "/images/blogs/7.webp",
    8: "/images/blogs/8.webp",
    9: "/images/blogs/9.webp",
    10: "/images/blogs/10.webp",
  },
  images: {
    // logo:"/images/logo.webp",
    subscribe: "/images/subscribe.svg",
    contact: "/images/contact.svg",
    homeAbout: "/images/about-us.webp",
    ourStory: "/images/our-story.png",
    aboutUs: "/images/about-us.png",
    joinOurTeam: "/images/careers.png",
    hero: "/images/hero.webp",
    homeFeature: "/images/home_features.webp",
    homeIndustryExperts: "/images/industryexpertise.webp",
    author: "/images/author.png",
    iconLogo: "/images/logos/icon-logo.png",
    iconLogoSVG: "/images/logos/icon-logo-svg.svg",
    nextjsLogo: "/images/nextjs-icon.png",
    notFound: "/images/not-found.svg",
    vision2030: "/images/vision2030.webp",
    project: {
      eCommerce: "/images/projects/1.png",
      medicalCenter: "/images/projects/2.png",
    },
    feature: {
      performance: "/images/features/performance.svg",
      growth: "/images/features/growth.webp",
      security: "/images/features/security.svg",
      responsive: "/images/features/responsive.svg",
      timely: "/images/features/timely.webp",
      localExpertise: "/images/features/locale.svg",
    },
    service: {
      logoDesign: "/images/services/logo-design.webp",
      uiUxDesign: "/images/services/ui-ux-design.webp",
      webDevelopment: "/images/services/web-development.webp",
      eInvoicing: "/images/services/e-invoicing.webp",
      mobileDevelopment: "/images/services/mobile-app-development.webp",
      digitalMarketing: "/images/services/digital-marketing.webp",
      customCmsDevelopment: "/images/services/custom-cms-development.webp",
      eCommerceSolutions: "/images/services/e-commerce-solutions.webp",
      brandIdentity: "/images/services/brand-identity.webp",
      apiDevelopment: "/images/services/api-development.webp",
      corporateProfile: "/images/services/corporate-profile.webp",
      printDesign: "/images/services/print-design.webp",
    },
    businessCategories: {
      retail: "/images/business-categories/retail.webp",
      smb: "/images/business-categories/smb.webp",
      healthcare: "/images/business-categories/healthcare.webp",
      education: "/images/business-categories/education.webp",
      corporate: "/images/business-categories/corporate.webp",
      manufacturing: "/images/business-categories/manufacturing.webp",
    },
    logo: {
      en: "/images/logos/en-logo.png",
      ar: "/images/logos/ar-logo.png",
      bn: "/images/logos/bn-logo.png",
    },
  },
  clients: {
    kullesh: "/images/clients/kullesh.webp",
    upf: "/images/clients/upf.webp",
    rightVisa: "/images/clients/right-visa.webp",
    nextRide: "/images/clients/next-ride.webp",
    ranchiUniversity: "/images/clients/ranchi-university.webp",
    sarah: "/images/clients/sarah.webp",
    kic: "/images/clients/kic.webp",
    deals: "/images/clients/deals.webp",
  },
};
