export const CONSTANT = {
  locales: ["en", "bn", "ar"],
  defaultLocale: "ar",
  blogs: {
    1: "/images/blogs/1.webp",
    2: "/images/blogs/2.webp",
    3: "/images/blogs/3.webp",
    4: "/images/blogs/4.webp",
    5: "/images/blogs/5.webp",
    6: "/images/blogs/6.webp",
    7: "/images/blogs/7.webp",
    8: "/images/blogs/8.webp",
    9: "/images/blogs/9.webp",
    10: "/images/blogs/10.webp",
  },
  images: {
    logo:"/images/logo.webp",
    subscribe: "/images/subscribe.svg",
    contact: "/images/contact.svg",
    homeAbout: "/images/about-us.webp",
    hero: "/images/hero.webp",
    homeFeature: "/images/home_features.webp",
    homeIndustryExperts: "/images/industryexpertise.webp",
    author: "/images/author.png",
  },
  clients: {
    kullesh: "/images/clients/kullesh.webp",
    upf: "/images/clients/upf.webp",
    rightVisa: "/images/clients/right-visa.webp",
    nextRide: "/images/clients/next-ride.webp",
    ranchiUniversity: "/images/clients/ranchi-university.webp",
    sarah: "/images/clients/sarah.webp",
    kic: "/images/clients/kic.webp",
    deals: "/images/clients/deals.webp",
  },
};
